name: CSEB_MID Docker Pipeline

on:
  workflow_run:
    workflows:
      - CSEB_MID CI Pipeline
    types:
      - completed

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/mahesh-65/cseb_mid:latest

jobs:

  docker:
    name: Build Scan Push GHCR
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Trivy Scan (Do Not Fail Pipeline)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          severity: HIGH,MEDIUM,CRITICAL
          exit-code: 0

      - name: Push Image to GHCR
        run: |
          docker push $IMAGE_NAME

      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CSEB_MID Docker Pipeline Success"
          body: |
            Hello Team,

            Docker image built, scanned and pushed successfully.

            Image:
            ${{ env.IMAGE_NAME }}

            Logs:
            https://github.com/${{ github.repository }}/actions

            Regards,
            DevSecOps Pipeline
          to: ${{ secrets.DEVOPS_EMAIL }}
          from: DevOps Alert

      - name: Send Failure Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CSEB_MID Docker Pipeline Failed"
          body: |
            Hello Team,

            Docker pipeline failed.

            Logs:
            https://github.com/${{ github.repository }}/actions

            Regards,
            DevSecOps Pipeline
          to: ${{ secrets.DEVOPS_EMAIL }}
          from: DevOps Alert